# Generated by Django 3.0.3 on 2020-05-02 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("examples", "0001_initial")]

    operations = [
        migrations.AddField(
            model_name="example",
            name="imagedetail1",
            field=models.ImageField(
                default="/Users/mm9684/django-template/portfolio-project/static/images/photo_MM.jpg",
                upload_to="images/",
            ),
        ),
        migrations.AddField(
            model_name="example",
            name="imagedetail2",
            field=models.ImageField(
                default="/Users/mm9684/django-template/portfolio-project/static/images/photo_MM.jpg",
                upload_to="images/",
            ),
        ),
        migrations.AddField(
            model_name="example",
            name="summarydetail",
            field=models.CharField(default="", max_length=500),
        ),
    ]
