# Generated by Django 3.0.3 on 2020-05-02 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("examples", "0002_auto_20200502_1302")]

    operations = [
        migrations.AlterField(
            model_name="example",
            name="summarydetail",
            field=models.CharField(default="", max_length=1500),
        )
    ]
